version: '3.8'

services:
  backend:
    image: itisnotstupid/chess-backend:latest
    container_name: chess-backend
    restart: always
    networks:
      - chess-network

  frontend: 
    image: itisnotstupid/chess-frontend:1.0.10
    container_name: chess-frontend
    restart: always
    networks:
      - chess-network

  nginx:
    image: nginx:alpine
    container_name: chess-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certbot-webroot:/var/www/certbot:ro 
      - ../certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - chess-network
 
networks:
  chess-network:
    driver: bridge
    name: chess-network