version: '3.8'

services:
  backend:
    image: itisnotstupid/chess-backend:latest
    container_name: preprod-chess-backend
    restart: always
    networks:
      - preprod-network

  frontend:
    image: itisnotstupid/chess-frontend:1.0.11
    container_name: preprod-chess-frontend
    restart: always
    networks:
      - preprod-network

  nginx:
    image: nginx:alpine
    container_name: preprod-nginx
    restart: always
    ports:
      - "1187:80"
      - "1188:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
      - ../certbot-webroot:/var/www/certbot:ro 
      - ../certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - preprod-network

networks:
  preprod-network:
    driver: bridge
    name: preprod-network